# Generated by Django 5.0.2 on 2024-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
