# Generated by Django 5.0.2 on 2024-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_scontact_alter_products_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='sorder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('Zip_code', models.CharField(max_length=90)),
            ],
        ),
    ]
