# Generated by Django 5.0.2 on 2024-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_sorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
